# Generated by Django 2.1.2 on 2018-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='uuid',
        ),
        migrations.AddField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, default=1223544, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
